version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /testjs.html
    destination: /var/www/html/tix/
  - source: /newer.html
    destination: /var/www/html/other/
  - source: scripts
    destination: /var/www/html/scripts
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
    - location: deregister_from_elb.sh
      timeout: 360
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: register_with_elb.sh
      timeout: 120
